# Generated by Django 4.2.11 on 2024-04-14 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
    ]
